### ISSUE TITLE
ConvertLocalLinks doesn't work

### ISSUE THREAD

**Issue by Grauenwolf** [FransBouma/DocNet#87]
ConvertLocalLinks doesn't appear to be working. 

Example: http://fransbouma.github.io/DocNet/markdownsupport.htm

> Docnet doesn't automatically transform links to markdown files by default. To enable automatic link conversion to local markdown files, please specify the ConvertLocalLinks option in the [docnet.json file](http://fransbouma.github.io/DocNet/docnetjson.md) file with the value true. If ConvertLocalLinks isn't specified or set to false, any link to any document in your documentation has to use the url it will get in the destination folder. 

The link points http://fransbouma.github.io/DocNet/docnetjson.md (a 404) instead of http://fransbouma.github.io/DocNet/docnetjson.htm.

Testing in my own project I'm seeing similar behavior.

**Comment by FransBouma** [comment]
Yeah it's buggy. It was an external contribution that worked in unit tests but fails in practice. The culprit is the 'PathSpecification' setting. Only if it's set to 'RelativeAsFolder' it will convert md to htm. Sigh... 

Fixing...

**Comment by FransBouma** [comment]
Fixed. Will update releases

**Comment by FransBouma** [comment]
Releases updated with 0.16.5 which should fix the problem.

**Comment by Grauenwolf** [comment]
I'm still seeing the same dead link on http://fransbouma.github.io/DocNet/markdownsupport.htm

**Comment by FransBouma** [comment]
I hadn't pushed the changes to the gh-pages branch. Should be ok now.
